version: "3"
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "8000:8000"
      - "9443:9443"
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"  # Mapeia o socket Docker
      - "/home/mbc/docker/portainer/data:/data"  # Mapeia a pasta local './data' para a pasta '/data' no container
      - "/home/mbc/docker/portainer/log:/var/log/portainer"  # Adicionando logs para Portainer
    networks:
      - portainer_network

networks:
  portainer_network:
    driver: bridge
